# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BCG_GenAI_The_Forage',
                'doc_host': 'https://Ramon-PR.github.io',
                'git_url': 'https://github.com/Ramon-PR/BCG_GenAI_The_Forage',
                'lib_path': 'BCG_GenAI_The_Forage'},
  'syms': {'BCG_GenAI_The_Forage.tools': {}}}
