# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_Load_financial_data.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_Load_financial_data.ipynb 2
import pandas as pd
import os
from pathlib import Path

# %% ../nbs/02_Load_financial_data.ipynb 25
import seaborn as sns
import matplotlib.pyplot as plt
